# nav2_params.yaml for SLAM-based navigation
amcl:
  ros__parameters:
    use_sim_time: false
    enabled: false  # Disable AMCL if using SLAM for localization

map_server:
  ros__parameters:
    use_sim_time: false
    enabled: false  # No static map needed if using SLAM Toolbox

slam_toolbox:
  ros__parameters:
    use_sim_time: false
    publish_period_sec: 2.0
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    max_laser_range: 15.0
    min_laser_range: 0.5
    sensor_max_range: 10.0
    grid_size: 0.05
    resolution: 0.05

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      height: 3.0  # Ensure it is a float value

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      height: 3.0  # Ensure it is a float value

bt_navigator:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 10.0
    rolling_window: true
    width: 3.0  # Float
    height: 3.0  # Float
    resolution: 0.05  # Float
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    rolling_window: false
    width: 10.0  # Float
    height: 10.0  # Float
    resolution: 0.05  # Float
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
